# Generated by Django 3.1.2 on 2021-12-11 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20211211_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_no',
            field=models.CharField(max_length=50),
        ),
    ]
